# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: DockerInstaller@0
    displayName: Install docker
    inputs:
      dockerVersion: 19.03.5
      releaseType: stable

  - bash: |
      sudo wget -O /usr/local/bin/buildx https://github.com/docker/buildx/releases/download/v0.3.1/buildx-v0.3.1.linux-amd64
      sudo chmod a+x /usr/local/bin/buildx
      docker run --rm --privileged hypriot/qemu-register
      buildx create --use
      buildx ls
    displayName: Setup docker buildx

  - bash: |
      buildx build \
        --build-arg NUGET_API_KEY=$(nugetApiKey) \
        --platform linux/arm64,linux/arm/v7 \
        -f Nick.Rpi.Driver.Bme280/Dockerfile \
        --push \
        -t nrandell/bme280.build \
        .
